[alembic]
# مسیر پوشه مایگریشن‌ها که با دستور init ساختیم
script_location = alembic

# نام دیتابیس (ما این را در env.py به صورت داینامیک از settings می‌خوانیم، پس اینجا مهم نیست)
sqlalchemy.url = postgresql+asyncpg://

[post_write_hooks]
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S