"""add iranian market fields and soft delete

Revision ID: d4552516cd6a
Revises: b51b18fa0c0b
Create Date: 2026-06-20 22:17:21.363825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4552516cd6a'
down_revision: Union[str, None] = 'b51b18fa0c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('brands', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('product_images', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('product_images', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('warranty_text', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('weight_grams', sa.Float(), nullable=True))
    
    # 👈 این ۳ خط اصلاح شدند: اضافه شدن server_default
    op.add_column('products', sa.Column('is_original', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('products', sa.Column('tax_percent', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'tax_percent')
    op.drop_column('products', 'is_original')
    op.drop_column('products', 'weight_grams')
    op.drop_column('products', 'warranty_text')
    op.drop_column('product_images', 'updated_at')
    op.drop_column('product_images', 'created_at')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('brands', 'updated_at')
    op.drop_column('brands', 'created_at')
    # ### end Alembic commands ###